-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 15:29:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nicolas_servico_ti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nicolas_servico_ti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nicolas_servico_ti` DEFAULT CHARACTER SET utf8 ;
USE `nicolas_servico_ti` ;

-- -----------------------------------------------------
-- Table `nicolas_servico_ti`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nicolas_servico_ti`.`tbl_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NULL,
  `telefone` VARCHAR(100) NULL,
  `celular` VARCHAR(100) NULL,
  `cpf` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NULL,
  `data_entrega` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `obeservacoes` VARCHAR(45) NULL,
  `caracteristicas_equipamentos` VARCHAR(45) NULL,
  `quiexa_cliente` VARCHAR(45) NULL,
  `valor_total` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `nicolas_servico_ti` ;

-- -----------------------------------------------------
-- Placeholder table for view `nicolas_servico_ti`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nicolas_servico_ti`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `nicolas_servico_ti`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicolas_servico_ti`.`view1`;
USE `nicolas_servico_ti`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
